### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

###

@baseUrl = http://localhost:3000/api/v1
@userId = 694ba141b0f831ce85276052


### Home endpoint - Check if server is running
GET {{baseUrl}}/ HTTP/1.1

### Create a new user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "johndoe",
  "email": "ahmed@email.com",
  "password": "securepassword123"
}

### Create another user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "janedoe",
  "email": "dada@email,com",
    "password": "anothersecurepassword"
}

### Create user - Missing required field (should fail)
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "email": "dd@email.com"
}

### Get all users
GET {{baseUrl}}/users HTTP/1.1

### Get one user by ID
# Replace the ID below with an actual ID from your database
GET {{baseUrl}}/users/{{userId}} HTTP/1.1

### Update a user by ID
# Replace the ID below with an actual ID from your database
PATCH  {{baseUrl}}/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "name": "johnupdated"
}

### Delete a user by ID
# Replace the ID below with an actual ID from your database
DELETE {{baseUrl}}/users/{{userId}} HTTP/1.1